roots : src/roots.c include/demo_fn.c include/demo_fn.h
	g++ -o bin/roots src/roots.c -lgsl -lgslcblas -I/home/jiminjun/Downloads/find_root/include/
report :
	xelatex doc/report.tex
	rm -r report.aux
	rm -r report.log
