report :
	@xelatex final
	@bibtex final
	@xelatex final
	@xelatex final
	@rm -r final.aux
	@rm -r final.bbl
	@rm -r final.log
	@rm -r final.blg
slide :
	@xelatex slide
	@rm -r slide.aux
	@rm -r slide.log
	@rm -r slide.nav
	@rm -r slide.out
	@rm -r slide.snm
	@rm -r slide.tex
	@rm -r slide.toc
	@rm -r texput.log
